export const GET_WELCOME_MESSAGE = "GET_WELCOME_MESSAGE";


//STATES
export const GET_STATES_LIST = "GET_STATES_LIST";
export const LOG_STATE_ERROR = "LOG_STATE_ERROR";

//DISTRICTS
export const GET_DISTRICT_LIST = "GET_DISTRICT_LIST";
export const LOG_DISTRICT_ERROR = "LOG_DISTRICT_ERROR";
//MEDIA
export const GET_MEDIA = "GET_MEDIA";

//BENEFICIARIES
export const GET_BENEFICIARY_LIST = "GET_BENEFICIARY_LIST";
export const LOG_BENEFICIARY_ERROR = "LOG_BENEFICIARY_ERROR";
export const STORE_CURRENT_BENEFICIARY = "STORE_CURRENT_BENEFICIARY";
export const GET_CURRENT_BENEFICIARY = "GET_CURRENT_BENEFICIARY";

//CROPS
export const GET_CROPS = "GET_CROPS";

//ROLES
export const GET_ROLES = "GET_ROLES";
export const GET_GENDERS = "GET_GENDERS";
export const GET_LANGUAGES = "GET_LANGUAGES";

//Login 
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_ERROR = "CHANGE_USER_PASSWORD_ERROR";