export const GET_WELCOME_MESSAGE = "GET_WELCOME_MESSAGE";

//STATES
export const GET_STATES_LIST = "GET_STATES_LIST";
export const LOG_STATE_ERROR = "LOG_STATE_ERROR";

//DISTRICTS
export const GET_DISTRICT_LIST = "GET_DISTRICT_LIST";
export const LOG_DISTRICT_ERROR = "LOG_DISTRICT_ERROR";

//GRAMPANCHAYAT
export const GET_GRAMPANCHAYAT_LIST = "GET_GRAMPANCHAYAT_LIST";
export const LOG_GRAMPANCHAYAT_ERROR = "LOG_GRAMPANCHAYAT_ERROR";
//VILLAGES
export const GET_VILLAGE_LIST = "GET_VILLAGE_LIST";
export const LOG_VILLAGE_ERROR = "LOG_VILLAGE_ERROR";

//MEDIA
export const GET_MEDIA = "GET_MEDIA";
export const STORE_AUDIO_FILES = "STORE_AUDIO_FILES";
export const STORE_VIDEO_FILES = "STORE_VIDEO_FILES";
export const STORE_IMAGE_FILES = "STORE_IMAGE_FILES";
export const LOG_IMAGE_ERROR = "LOG_IMAGE_ERROR";
export const LOG_VIDEO_ERROR = "LOG_VIDEO_ERROR";
export const LOG_AUDIO_ERROR = "LOG_AUDIO_ERROR";


//BENEFICIARIES
export const GET_BENEFICIARY_LIST = "GET_BENEFICIARY_LIST";
export const LOG_BENEFICIARY_ERROR = "LOG_BENEFICIARY_ERROR";
export const STORE_CURRENT_BENEFICIARY = "STORE_CURRENT_BENEFICIARY";
export const GET_CURRENT_BENEFICIARY = "GET_CURRENT_BENEFICIARY";
export const STORE_BULK_UPLOAD_HISTORY = "STORE_BULK_UPLOAD_HISTORY";
export const CLEAR_BENEFICIARY_ERROR = "CLEAR_BENEFICIARY_ERROR";
export const VALIDATE_BULKDATA_ERROR = "VALIDATE_BULKDATA_ERROR";
export const VALIDATE_BULKDATA_SUCCESS = "VALIDATE_BULKDATA_SUCCESS";

//CROPS
export const GET_CROPS = "GET_CROPS";
export const GET_CURRENT_CROP_DATA = "GET_CURRENT_CROP_DATA";
export const GET_CROPS_STEPS = "GET_CROPS_STEPS";
export const GET_CROPS_STEPS_MATERIAL = "GET_CROPS_STEPS_MATERIAL";
export const STORE_CROP_AUDIO_ALLOCATION = "STORE_CROP_AUDIO_ALLOCATION";
export const STORE_CROP_STEP_AUDIO_ALLOCATION =
  "STORE_CROP_STEP_AUDIO_ALLOCATION";
export const STORE_CROP_MATERIAL_AUDIO_ALLOCATION =
  "STORE_CROP_MATERIAL_AUDIO_ALLOCATION";
export const LOG_CROP_ERROR = "LOG_CROP_ERROR";
export const LOG_CROP_STEP_ERROR = "LOG_CROP_STEP_ERROR";
export const LOG_CROP_MATERIAL_ERROR = "LOG_CROP_MATERIAL_ERROR";

//ROLES
export const GET_ROLES = "GET_ROLES";
export const LOG_ROLE_ERROR = "LOG_ROLE_ERROR";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";

//GENDERS
export const GET_GENDERS = "GET_GENDERS";
export const LOG_GENDER_ERROR = "LOG_GENDER_ERROR";
export const CREATE_GENDER_SUCCESS = "CREATE_GENDER_SUCCESS";
export const UPDATE_GENDER_SUCCESS = "UPDATE_GENDER_SUCCESS";

//LANGUAGES
export const GET_LANGUAGES = "GET_LANGUAGES";
export const LOG_LANGUAGE_ERROR = "LOG_LANGUAGE_ERROR";
export const CREATE_LANGUAGE_SUCCESS = "CREATE_LANGUAGE_SUCCESS";
export const UPDATE_LANGUAGE_SUCCESS = "UPDATE_LANGUAGE_SUCCESS";

//Login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_ERROR = "CHANGE_USER_PASSWORD_ERROR";


//feedback
export const STORE_FEEDBACK_QUESTIONS = "STORE_FEEDBACK_QUESTIONS";
export const LOG_FEEDBACK_QUESTIONS_ERROR = "LOG_FEEDBACK_QUESTIONS_ERROR";
export const STORE_USER_FEEDBACKS = "STORE_USER_FEEDBACKS";
export const LOG_USER_FEEDBACK_ERROR = "LOG_USER_FEEDBACK_ERROR";